<?php
/**
 * Created by Claudio Campos.
 * User: callcocam@gmail.com
 * https://www.sigasmart.com.br
 */

namespace App\Models\Admin;


use App\AbstractModel;
use Illuminate\Support\Facades\DB;

class Order extends AbstractModel
{

    protected $fillable = [
        'user_id','number','client_id','price','discount','affix','total','delivery_date','status', 'description','updated_at',
    ];


    public function saveBy($data)
    {
        if (isset($data['price']))
        $data['price'] = form_w($data['price']);

        return parent::saveBy($data); // TODO: Change the autogenerated stub
    }

    public function items(){

        return $this->hasMany(Item::class);
    }

    public function itemsProducts(){

        $items = $this->hasMany(Item::class)->get();

        return $items;
    }
    public function client(){

        return $this->belongsTo(Client::class);
    }
}
